name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'app/**'
      - '.github/workflows/deploy.yml'

env:
  RESOURCE_GROUP: RSG-GHBot-285
  ACR: containerregistryGHBot285.azurecr.io
  APP_NAME: webapp-GHBot-285

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 'Login via Azure CLI'
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.ACR }}/veta-agents:latest
          ${{ env.ACR }}/veta-agents:${{ github.run_number }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        resource-group-name: ${{ env.RESOURCE_GROUP }}
        app-name: ${{ env.APP_NAME }}
        images: '${{ env.ACR }}/veta-agents:${{ github.run_number }}'

